# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: polysim.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='polysim.proto',
  package='polysim',
  serialized_pb=_b('\n\rpolysim.proto\x12\x07polysim\"+\n\x08SPolymer\x12\t\n\x01x\x18\x01 \x03(\x01\x12\t\n\x01y\x18\x02 \x03(\x01\x12\t\n\x01z\x18\x03 \x03(\x01\"*\n\x07SSystem\x12\x1f\n\x04poly\x18\x01 \x03(\x0b\x32\x11.polysim.SPolymer\"n\n\x04SSim\x12 \n\x06system\x18\x01 \x03(\x0b\x32\x10.polysim.SSystem\x12\x1f\n\x04yolk\x18\x03 \x03(\x0b\x32\x11.polysim.SPolymer\x12#\n\x08settings\x18\x02 \x02(\x0b\x32\x11.polysim.Settings\"|\n\x08Settings\x12\t\n\x01h\x18\x08 \x02(\x01\x12\n\n\x02sk\x18\x01 \x02(\x01\x12\n\n\x02pk\x18\x02 \x02(\x01\x12\x0e\n\x06stiffk\x18\x03 \x02(\x01\x12\x0e\n\x06shiftk\x18\x04 \x02(\x01\x12\x0e\n\x06oseenk\x18\x05 \x02(\x01\x12\r\n\x05\x62\x61sek\x18\x06 \x02(\x01\x12\x0e\n\x06numpin\x18\x07 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPOLYMER = _descriptor.Descriptor(
  name='SPolymer',
  full_name='polysim.SPolymer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='polysim.SPolymer.x', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='polysim.SPolymer.y', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='polysim.SPolymer.z', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=69,
)


_SSYSTEM = _descriptor.Descriptor(
  name='SSystem',
  full_name='polysim.SSystem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poly', full_name='polysim.SSystem.poly', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=113,
)


_SSIM = _descriptor.Descriptor(
  name='SSim',
  full_name='polysim.SSim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='system', full_name='polysim.SSim.system', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yolk', full_name='polysim.SSim.yolk', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='settings', full_name='polysim.SSim.settings', index=2,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=225,
)


_SETTINGS = _descriptor.Descriptor(
  name='Settings',
  full_name='polysim.Settings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='h', full_name='polysim.Settings.h', index=0,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sk', full_name='polysim.Settings.sk', index=1,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pk', full_name='polysim.Settings.pk', index=2,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stiffk', full_name='polysim.Settings.stiffk', index=3,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shiftk', full_name='polysim.Settings.shiftk', index=4,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oseenk', full_name='polysim.Settings.oseenk', index=5,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='basek', full_name='polysim.Settings.basek', index=6,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numpin', full_name='polysim.Settings.numpin', index=7,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=351,
)

_SSYSTEM.fields_by_name['poly'].message_type = _SPOLYMER
_SSIM.fields_by_name['system'].message_type = _SSYSTEM
_SSIM.fields_by_name['yolk'].message_type = _SPOLYMER
_SSIM.fields_by_name['settings'].message_type = _SETTINGS
DESCRIPTOR.message_types_by_name['SPolymer'] = _SPOLYMER
DESCRIPTOR.message_types_by_name['SSystem'] = _SSYSTEM
DESCRIPTOR.message_types_by_name['SSim'] = _SSIM
DESCRIPTOR.message_types_by_name['Settings'] = _SETTINGS

SPolymer = _reflection.GeneratedProtocolMessageType('SPolymer', (_message.Message,), dict(
  DESCRIPTOR = _SPOLYMER,
  __module__ = 'polysim_pb2'
  # @@protoc_insertion_point(class_scope:polysim.SPolymer)
  ))
_sym_db.RegisterMessage(SPolymer)

SSystem = _reflection.GeneratedProtocolMessageType('SSystem', (_message.Message,), dict(
  DESCRIPTOR = _SSYSTEM,
  __module__ = 'polysim_pb2'
  # @@protoc_insertion_point(class_scope:polysim.SSystem)
  ))
_sym_db.RegisterMessage(SSystem)

SSim = _reflection.GeneratedProtocolMessageType('SSim', (_message.Message,), dict(
  DESCRIPTOR = _SSIM,
  __module__ = 'polysim_pb2'
  # @@protoc_insertion_point(class_scope:polysim.SSim)
  ))
_sym_db.RegisterMessage(SSim)

Settings = _reflection.GeneratedProtocolMessageType('Settings', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGS,
  __module__ = 'polysim_pb2'
  # @@protoc_insertion_point(class_scope:polysim.Settings)
  ))
_sym_db.RegisterMessage(Settings)


# @@protoc_insertion_point(module_scope)
